"""added comment status attribute

Revision ID: 0552d12134f4
Revises: 5b622d252ff1
Create Date: 2023-11-07 00:24:10.407377

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0552d12134f4'
down_revision = '5b622d252ff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='0-pending, 1-approved, 2-completed',
               existing_nullable=True)

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('service_title',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('service_title',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.SMALLINT(display_width=6),
               comment=None,
               existing_comment='0-pending, 1-approved, 2-completed',
               existing_nullable=True)

    # ### end Alembic commands ###
