"""added comment attribute staff.position

Revision ID: 52257ec9a7dd
Revises: 5cb2ea94f65d
Create Date: 2023-11-07 02:45:21.662390

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '52257ec9a7dd'
down_revision = '5cb2ea94f65d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.alter_column('position',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='0-master, 1-dentist, 2-hygienist, 3-receiptionist',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.alter_column('position',
               existing_type=mysql.SMALLINT(display_width=6),
               comment=None,
               existing_comment='0-master, 1-dentist, 2-hygienist, 3-receiptionist',
               existing_nullable=True)

    # ### end Alembic commands ###
