"""empty message

Revision ID: 57898c0e9eaf
Revises: 
Create Date: 2024-01-23 17:12:03.434192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '57898c0e9eaf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('amount_paid', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tooth_number', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('treatment', sa.String(length=255), nullable=True))
        batch_op.alter_column('status',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='0-pending, 1-approved, 2-completed',
               existing_nullable=True)
        batch_op.drop_column('service_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.alter_column('status',
               existing_type=mysql.SMALLINT(display_width=6),
               comment=None,
               existing_comment='0-pending, 1-approved, 2-completed',
               existing_nullable=True)
        batch_op.drop_column('treatment')
        batch_op.drop_column('tooth_number')
        batch_op.drop_column('amount_paid')
        batch_op.drop_column('request_time')

    op.create_table('services',
    sa.Column('service_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('service_title', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('service_description', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('service_price', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('service_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
