"""admin table  now related to staff table

Revision ID: 5cb2ea94f65d
Revises: 0552d12134f4
Create Date: 2023-11-07 02:42:58.540840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5cb2ea94f65d'
down_revision = '0552d12134f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_id', sa.Integer(), nullable=False))
        batch_op.drop_column('firstname')
        batch_op.drop_column('lastname')
        batch_op.drop_column('email')
        batch_op.drop_column('contact_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_number', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('lastname', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('firstname', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('staff_id')

    # ### end Alembic commands ###
