"""empty message

Revision ID: ad32d77df234
Revises: 57898c0e9eaf
Create Date: 2024-01-23 18:24:59.474656

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad32d77df234'
down_revision = '57898c0e9eaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tooth', sa.String(length=255), nullable=True))
        batch_op.drop_column('tooth_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tooth_number', mysql.VARCHAR(length=10), nullable=True))
        batch_op.drop_column('tooth')

    # ### end Alembic commands ###
