"""empty message

Revision ID: d19e4a0a985a
Revises: eabb5f7c60c4
Create Date: 2023-12-20 19:05:43.788545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd19e4a0a985a'
down_revision = 'eabb5f7c60c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.Integer(), nullable=True))
        batch_op.drop_column('treatment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('treatment', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('service_id')

    # ### end Alembic commands ###
