"""empty message

Revision ID: eabb5f7c60c4
Revises: fd210023dcfc
Create Date: 2023-12-20 16:50:12.062779

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eabb5f7c60c4'
down_revision = 'fd210023dcfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('treatment', sa.String(length=100), nullable=True))

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('treatment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('treatment', mysql.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('treatment')

    # ### end Alembic commands ###
